---
# tasks file for apache
- name: Install Apache package for CentOS
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Apache package for Ubuntu
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure Apache service is started and enabled
  service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: started
    enabled: yes

- name: Install PHP and required extensions for CentOS
  yum:
    name:
      - php
      - php-mysqlnd
    state: present
  when: ansible_os_family == "RedHat"
  notify: Restart Apache CentOS

- name: Install PHP and required extensions for Ubuntu
  apt:
    name:
      - php
      - php-mysql
    state: present
  when: ansible_os_family == "Debian"
  notify: Restart Apache Debian
