apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: wordpress
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env:
        - name: WORDPRESS_DB_HOST
          value: "{{ .Release.Name }}-mysql-db"
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: mysql-database
        ports:
        - containerPort: 80
          name: wordpress
        resources:
          {{- toYaml .Values.wordpress.resources | nindent 10 }}
        volumeMounts:
        - name: wp-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc